---
services:
  # NOTE: do NOT include dash(-) in your service name. Use underscore instead.
  # Example service name that contains dash: hello-world-blah
  # As we use "-" in nghttpx config to connect service name and hostname,
  # "-" is used as a delimiter in dispatcher to parse out service names.

  hello:
    ip_address: 127.0.0.1
    port: 50050
  magmad:
    ip_address: 127.0.0.1
    port: 50052
  control_proxy:
    ip_address: 127.0.0.1
    port: 50053
  subscriberdb:
    ip_address: 127.0.0.1
    port: 50051
  mobilityd:
    ip_address: 127.0.0.1
    port: 60051
  metering:
    ip_address: 127.0.0.1
    port: 60052
  enodebd:
    ip_address: 127.0.0.1
    port: 60055
  mme:
    ip_address: 127.0.0.1
    port: 50061
  spgw:
    ip_address: 127.0.0.1
    port: 50062
  pipelined:
    ip_address: 127.0.0.1
    port: 50063
  s6a_service:
    ip_address: 127.0.0.1
    port: 50064
  sessiond:
    ip_address: 127.0.0.1
    port: 50065
  test_service:
    ip_address: 127.0.0.1
    port: 50066
  directoryd:
    ip_address: 127.0.0.1
    port: 50067
  policydb:
    ip_address: 127.0.0.1
    port: 50068
  sgs_service:
    ip_address: 127.0.0.1
    port: 50069
  vpnservice:
    ip_address: 127.0.0.1
    port: 50070
  redirectd:
    ip_address: 127.0.0.1
    port: 50071
  captive_portal:
    ip_address: 127.0.0.1
    port: 50072
  spgw_service:
    ip_address: 127.0.0.1
    port: 50073
