{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.nginx.create }}
{{- $serviceName := print .Release.Name "-nginx" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: nginx-proxy
{{ include "labels" . | indent 4 }}
spec:
  replicas: {{ .Values.nginx.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: nginx-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: nginx-proxy
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.nginx.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nginx.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.nginx.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}
      volumes:
        - name: certs
          secret:
            secretName: {{ required "secret.certs must be provided" .Values.secret.certs }}
        - name: envdir
          secret:
            secretName: {{ required "secret.envdir must be provided" .Values.secret.envdir }}
      containers:
        - name: {{ $serviceName }}
          image: {{ required "nginx.image.repository must be provided" .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          volumeMounts:
            {{- range tuple "certs" "envdir" }}
            - name: {{ . }}
              mountPath: /var/opt/magma/{{ . }}
              readOnly: true
            {{- end }}
          ports:
            - name: clientcert
              containerPort: {{ .Values.nginx.service.port.clientcert.targetPort }}
            - name: open
              containerPort: {{ .Values.nginx.service.port.open.targetPort }}
            - name: api
              containerPort: {{ .Values.nginx.service.port.api.targetPort }}
            - name: health
              containerPort: {{ .Values.nginx.service.port.health.targetPort }}
          env:
            - name: PROXY_BACKENDS
              value: {{ print .Release.Name "-controller" | quote }}
            - name: CONTROLLER_HOSTNAME
              value: {{ required "nginx.spec.hostname must be provided" .Values.nginx.spec.hostname | quote }}
            - name: RESOLVER
              value: "kube-dns.kube-system.svc.cluster.local"
          livenessProbe:
            tcpSocket:
              port: health
            initialDelaySeconds: 10
            periodSeconds: 30
          readinessProbe:
            tcpSocket:
              port: health
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
{{ toYaml .Values.nginx.resources | indent 12 }}
{{- end }}
