---
swagger: '2.0'
info:
  title: Devmand Model Definitions and Paths
  description: Magma REST APIs
  version: 1.1.2

tags:
- name: Devmand
  description: Devmand devices attached to the network

paths:
  /networks/{network_id}/configs/devices:
    get:
      summary: Get all devices in the network
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/all_managed_devices'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Create a new device with config
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: query
        name: requested_id
        type: string
        description: The id of the device requested by user
        pattern: '^[a-z_][\da-z_]+$'
        minLength: 1
        maxLength: 100
        required: true
      - in: body
        name: Managed Device
        description: New managed device properties
        required: true
        schema:
          $ref: '#/definitions/managed_device'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /networks/{network_id}/configs/devices/{device_id}:
    get:
      summary: Retrieve a device's config
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/device_id'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/managed_device'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify a device's config
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/device_id'
      - in: body
        name: config
        description: New device config
        required: true
        schema:
          $ref: '#/definitions/managed_device'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete a device's config
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/device_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
  /networks/{network_id}/gateways/{gateway_id}/configs/devmand:
    post:
      summary: Create gateway devmand configs
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: New devmand config
        required: true
        schema:
          $ref: '#/definitions/gateway_devmand_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve gateway devmand configs
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Success
          schema:
            $ref: '#/definitions/gateway_devmand_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify the gateway devmand configs
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/gateway_devmand_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete gateway devmand configs
      tags:
      - Devmand
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  gateway_devmand_configs:
    description: Configuration for devmand
    type: object
    minLength: 1
    properties:
      managed_devices:
        type: array
        items:
          type: string
          minLength: 1
          x-nullable: false
        example: ['device_1', 'device_2']
  all_managed_devices:
    description: List of device IDs
    type: array
    items:
      type: string
      minLength: 1
    example: ['device_1', 'device_2']
  managed_device:
    description: Management properties for a given device
    type: object
    minLength: 1
    properties:
      device_config:
        # Use arbitary object here later once we're ready, for now use
        # a JSON string
        type: string
        x-nullable: false
        example:
          '{
            "interfaces": {
              "interface": [
                {
                  "config": {
                    "description": "ACCESS PORT",
                    "name": "g0/0/0",
                    "type": "ethernetCsmacd"
                  },
                  "name": "g0/0/0"
                }
              ]
            }
          }'
      host:
        type: string
        x-nullable: false
        example:
          '1.2.3.4'
      device_type:
        type: array
        items:
          type: string
          minLength: 1
          x-nullable: false
        example: ['wifi', 'access_point']
      platform:
        type: string
        x-nullable: false
        example:
          Ubiquiti
      channels:
        type: object
        properties:
          snmp_channel:
            $ref: '#/definitions/snmp_channel'
            x-nullable: true
          frinx_channel:
            $ref: '#/definitions/frinx_channel'
            x-nullable: true
          cambium_channel:
            $ref: '#/definitions/cambium_channel'
            x-nullable: true
          other_channel:
            $ref: '#/definitions/other_channel'
            x-nullable: true
  snmp_channel:
    description: An SNMP channel definition
    type: object
    minLength: 1
    properties:
      version:
        type: string
        minLength: 1
        x-nullable: false
        example: v1
      community:
        type: string
        minLength: 1
        x-nullable: false
        example: public
  frinx_channel:
    description: A frinx channel definition
    type: object
    minLength: 1
    properties:
      frinx_port:
        type: integer
        format: int32
        minLength: 1
        x-nullable: false
        example: 8181
      authorization:
        type: string
        minLength: 1
        x-nullable: false
        example: Basic
      host:
        type: string
        minLength: 1
        x-nullable: false
        example: 10.0.0.1
      port:
        type: integer
        format: int32
        minLength: 1
        x-nullable: false
        example: 22
      transport_type:
        type: string
        minLength: 1
        x-nullable: false
        example: ssh
      device_type:
        type: string
        minLength: 1
        x-nullable: false
        example: ubnt es
      device_version:
        type: string
        minLength: 1
        x-nullable: false
        example: 1.8.2
      username:
        type: string
        minLength: 1
        x-nullable: false
      password:
        type: string
        minLength: 1
        x-nullable: false
  cambium_channel:
    description: A cambium channel definition
    type: object
    minLength: 1
    properties:
      client_id:
        type: string
        minLength: 1
        x-nullable: false
        example: Ya4dNAAYSUoFMUSs
      client_secret:
        type: string
        minLength: 1
        x-nullable: false
        example: 2kBgGnMr69NgNdeHB3s7x4GzUODLkc
      client_mac:
        type: string
        minLength: 1
        x-nullable: false
        example: 58:C1:7A:90:36:50
      client_ip:
        type: string
        minLength: 1
        x-nullable: false
        example: 10.0.0.1
  other_channel:
    description: A generic channel definition
    type: object
    minLength: 1
    properties:
      channel_props:
        type: object
        minLength: 1
        x-nullable: false
        additionalProperties:
          type: string
        example:
          channel_prop: prop_value
          another_channel_prop: another_prop_value
