---
swagger: '2.0'
info:
  title: Magma
  description: Magma REST APIs
  version: 1.1.2

paths:
  /networks/{network_id}/configs/federation:
    post:
      summary: Create Network FeG Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/network_federation_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Network FeG Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: Retrieved Network FeG Configs
          schema:
            $ref: '#/definitions/network_federation_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Network FeG Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/network_federation_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Network FeG Configs
      tags:
      - Networks
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/gateways/{gateway_id}/configs/federation:
    post:
      summary: Create Gateway FeG Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: New config
        required: true
        schema:
          $ref: '#/definitions/network_federation_configs'
      responses:
        '201':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    get:
      summary: Retrieve Gateway FeG Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '200':
          description: Retrieved Gateway FeG Configs
          schema:
            $ref: '#/definitions/network_federation_configs'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify Gateway FeG Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      - in: body
        name: config
        description: Updated config
        required: true
        schema:
          $ref: '#/definitions/gateway_feg_configs'
      responses:
        '200':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Delete Gateway FeG Configs
      tags:
      - Gateways
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/gateway_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

definitions:
  network_federation_configs:
    description: Federation configuration for a network
    type: object
    minLength: 1
    properties:
      s6a:
        type: object
        properties:
          server:
            $ref: '#/definitions/diameter_client_configs'
        x-go-custom-tag: 'magma_alt_name:"S6A"'
      hss:
        type: object
        properties:
          server:
            $ref: '#/definitions/diameter_server_configs'
          lte_auth_op:
            type: string
            format: byte
            example: EREREREREREREREREREREQ==
          lte_auth_amf:
            type: string
            format: byte
            example: gAA=
          default_sub_profile:
            $ref: '#/definitions/subscription_profile'
          sub_profiles:
            type: object
            additionalProperties:
              $ref: '#/definitions/subscription_profile'
          stream_subscribers:
            type: boolean
            example: false
        x-go-custom-tag: 'magma_alt_name:"HSS"'
      gx:
        type: object
        properties:
          server:
            $ref: '#/definitions/diameter_client_configs'
      gy:
        type: object
        properties:
          server:
            $ref: '#/definitions/diameter_client_configs'
          init_method:
            type: integer
            format: uint32
            enum:
            # 1 - Gx Init Method PER_SESSION
            - 1
            # 2 - Gx Init Method PER_KEY
            - 2
            default: 1
      swx:
        type: object
        properties:
          server:
            $ref: '#/definitions/diameter_client_configs'
          verify_authorization:
            type: boolean
            example: false
          register_on_auth:
            type: boolean
            example: false
          derive_unregister_realm:
            type: boolean
            example: false
          cache_TTL_seconds:
            type: integer
            format: uint32
            x-nullable: false
            default: 10800
            example: 10800
        x-go-custom-tag: 'magma_alt_name:"SWX"'
      eap_aka:
        type: object
        properties:
          timeout:
            $ref: '#/definitions/eap_aka_timeouts'
          plmn_ids:
            type: array
            items:
              type: string
              minLength: 5
              maxLength: 6
              pattern: '^(\d{5,6})$'
              example: '123456'
      aaa_server:
        type: object
        properties:
          idle_session_timeout_ms:
            type: integer
            format: uint32
            x-nullable: false
            example: 21600000
            default: 21600000
            x-go-custom-tag: 'magma_alt_name:"IdleSessionTimeoutMs"'
          accounting_enabled:
            type: boolean
            x-nullable: false
            example: false
            default: false
          create_session_on_auth:
            type: boolean
            x-nullable: false
            example: false
            default: false
      served_network_ids:
        type: array
        items:
          type: string
      health:
        type: object
        properties:
          health_services:
            description: FeG services for the health service to monitor
            type: array
            items:
              type: string
              enum:
              - S6A_PROXY
              - SESSION_PROXY
              - SWX_PROXY
            example:
            - S6A_PROXY
            - SESSION_PROXY
            x-go-custom-tag: 'magma_alt_name:"RequiredServices"'
          update_interval_secs:
            type: integer
            format: uint32
            example: 10
          cloud_disable_period_secs:
            type: integer
            format: uint32
            example: 10
            x-go-custom-tag: 'magma_alt_name:"CloudDisconnectPeriodSecs"'
          local_disable_period_secs:
            type: integer
            format: uint32
            example: 1
            x-go-custom-tag: 'magma_alt_name:"LocalDisconnectPeriodSecs"'
          update_failure_threshold:
            type: integer
            format: uint32
            example: 3
          request_failure_threshold:
            type: number
            format: float
            example: 0.50
          minimum_request_threshold:
            type: integer
            format: uint32
            example: 1
          cpu_utilization_threshold:
            type: number
            format: float
            example: 0.90
            x-go-custom-tag: 'magma_alt_name:"CpuUtilizationThreshold"'
          memory_available_threshold:
            type: number
            format: float
            example: 0.90
        x-go-custom-tag: 'magma_alt_name:"HEALTH"'
  eap_aka_timeouts:
    type: object
    properties:
      challenge_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 20000
        example: 20000
      error_notification_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 10000
        example: 10000
      session_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 43200000
        example: 43200000
      session_authenticated_ms:
        type: integer
        format: uint32
        x-nullable: false
        default: 5000
        example: 5000
  diameter_client_configs:
    description: Diameter Configuration of The Client
    type: object
    minLength: 1
    properties:
      protocol:
        type: string
        enum:
        - tcp
        - tcp4
        - tcp6
        - sctp
        - sctp4
        - sctp6
        default: tcp
        example: tcp
        x-nullable: false
      address:
        type: string
        pattern: '[^\:]+(:[0-9]{1,5})?'
        example: "foo.bar.com:5555"
        x-nullable: false
      retransmits:
        type: integer
        format: uint32
        default: 3
        x-nullable: false
      watchdog_interval:
        type: integer
        format: uint32
        default: 1
        x-nullable: false
      retry_count:
        type: integer
        format: uint32
        default: 5
        x-nullable: false
      local_address:
        type: string
        pattern: '[0-9a-f\:\.]*(:[0-9]{1,5})?'
        example: ":56789"
        x-nullable: false
      product_name:
        type: string
        minLength: 1
        default: "magma"
        x-nullable: false
      realm:
        type: string
        minLength: 1
        default: "magma.com"
        x-nullable: false
      host:
        type: string
        minLength: 1
        default: "magma-fedgw.magma.com"
        x-nullable: false
      dest_realm:
        type: string
        example: "magma.com"
        x-nullable: false
      dest_host:
        type: string
        example: "magma-fedgw.magma.com"
        x-nullable: false
      disable_dest_host:
        type: boolean
        x-nullable: false
        example: false
        default: false

  diameter_server_configs:
    description: Diameter Configuration of The Server
    type: object
    minLength: 1
    properties:
      protocol:
        type: string
        enum:
        - tcp
        - tcp4
        - tcp6
        - sctp
        - sctp4
        - sctp6
        default: tcp
        example: tcp
        x-nullable: false
      address:
        type: string
        pattern: '[^\:]+(:[0-9]{1,5})?'
        example: "foo.bar.com:5555"
        x-nullable: false
      local_address:
        type: string
        pattern: '[0-9a-f\:\.]*(:[0-9]{1,5})?'
        example: ":56789"
        x-nullable: false
      dest_realm:
        type: string
        example: "magma.com"
        x-nullable: false
      dest_host:
        type: string
        example: "magma-fedgw.magma.com"
        x-nullable: false

  subscription_profile:
    description: HSS Subscription Profile
    type: object
    minLength: 1
    properties:
      max_ul_bit_rate:
        type: integer
        format: uint64
        example: 100000000
        x-nullable: false
      max_dl_bit_rate:
        type: integer
        format: uint64
        example: 200000000
        x-nullable: false

  gateway_feg_configs:
    $ref: '#/definitions/network_federation_configs'