---

#TODO: presumes magma-helm directory is available on github
#

- name: publish helm charts
  command: "/usr/bin/bash package.sh -d {{ magmaDeploymentType }} "
  args:
    chdir: "{{ magmaPackageDir }}"

- name: verify helm charts
  script: "roles/build-service/files/helm-verify.bash {{ gitUser }} {{ gitPat }} {{ gitHelmRepo }}" 

