---
swagger: '2.0'
info:
  title: Meteringd Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

magma-gen-meta:
  go-package: magma/orc8r/cloud/go/pluginimpl/models
  dependencies:
    - 'orc8r/cloud/go/models/swagger-common.yml'
    - 'lte/cloud/go/plugin/models/swagger.v1.yml'
  temp-gen-filename: lte-metering-swagger.yml
  output-dir: lte/cloud/go/services/meteringd_records/obsidian
  types:
    - go-struct-name: FlowRecord
      filename: flow_record_swaggergen.go

tags:
  - name: Metering
    description: Operations related to data usage metering

basePath: /magma/v1

paths:
  /networks/{network_id}/subscribers/{subscriber_id}/flow_records:
    get:
      summary: Retrieves the usage records for the subscriber
      tags:
        - Subscribers
        - Metering
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-swagger.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Subscriber usage records
          schema:
            type: array
            items:
              $ref: '#/definitions/flow_record'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

definitions:
  flow_record:
    type: object
    required:
      - subscriber_id
      - bytes_rx
      - bytes_tx
      - pkts_tx
      - pkts_rx
    properties:
      subscriber_id:
        type: string
        x-nullable: false
        example: 'IMSI1234567890'
      bytes_tx:
        type: integer
        format: uint64
      bytes_rx:
        type: integer
        format: uint64
      pkts_tx:
        type: integer
        format: uint64
      pkts_rx:
        type: integer
        format: uint64