---
swagger: '2.0'
info:
  title: Meteringd Model Definitions and Paths
  description: Magma REST APIs
  version: 1.0.0

tags:
  - name: Flow Records
    description: Operations for viewing traffic flow usage records

paths:
  # Service paths
  /networks/{network_id}/subscribers/{subscriber_id}/flow_records:
    get:
      summary: Retrieves the flow records for the subscriber
      tags:
      - Subscribers
      - Flow Records
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: './swagger-common.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Subscriber flow records
          schema:
            type: array
            items:
              $ref: '#/definitions/flow_record'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

  /networks/{network_id}/flow_records/{flow_record_id}:
    get:
      summary: Get flow record
      tags:
      - Flow Records
      parameters:
      - $ref: './swagger-common.yml#/parameters/network_id'
      - $ref: '#/parameters/flow_record_id'
      responses:
        '200':
          description: Flow record on success
          schema:
            $ref: '#/definitions/flow_record'
        default:
          $ref: './swagger-common.yml#/responses/UnexpectedError'

parameters:
  flow_record_id:
    in: path
    name: flow_record_id
    description: Flow Record ID
    required: true
    type: string

definitions:
  flow_record_id:
    # A uuid generated on the AG for each meter record and uniquely
    # identifies a subscriber session of a flow rule
    type: string
    minLength: 1
    x-nullable: false
    example: 22ffea10-7fc4-4427-975a-b9e4ce8f6f4d
  flow_match:
    # A template for matching traffic to meter
    type: object
    properties:
      ip_proto:
        type: string
        enum:
        - IPPROTO_IP
        - IPPROTO_TCP
        - IPPROTO_UDP
        - IPPROTO_ICMP
        x-nullable: true
        default: IPPROTO_IP
      ipv4_src:
        type: string
        format: ip-address
        example: "192.168.0.1/24"
        x-go-custom-tag: 'magma_alt_name:"Ipv4Src"'
      ipv4_dst:
        type: string
        format: ip-address
        example: "0.0.0.0/0"
        x-go-custom-tag: 'magma_alt_name:"Ipv4Dst"'
      tcp_src:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"TcpSrc"'
      tcp_dst:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"TcpDst"'
      udp_src:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"UdpSrc"'
      udp_dst:
        type: integer
        format: uint32
        x-go-custom-tag: 'magma_alt_name:"UdpDst"'
      direction:
        type: string
        enum:
        - UPLINK
        - DOWNLINK
        x-nullable: false
  flow_record:
    # A usage record tracks a subscriber's usage for a defined class of traffic
    type: object
    properties:
      subscriber_id:
        $ref: './swagger-common.yml#/definitions/subscriber_id'
        x-nullable: false
        x-go-custom-tag: 'magma_alt_name:"Sid"'
      bytes_tx:
        type: integer
        format: uint64
      bytes_rx:
        type: integer
        format: uint64
      pkts_tx:
        type: integer
        format: uint64
      pkts_rx:
        type: integer
        format: uint64