{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.configmanager.create }}
{{- $serviceName := print .Release.Name "-configmanager" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: configmanager
{{ include "metrics.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.configmanager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: configmanager
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: configmanager
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.configmanager.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.configmanager.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.configmanager.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      volumes:
        - name: "prometheus-config"
{{ toYaml .Values.metrics.volumes.prometheusConfig.volumeSpec | indent 10 }}

      containers:
        - name: "config-manager"
          image: {{ required "configmanager.image.repository must be provided" .Values.configmanager.image.repository }}:{{ .Values.configmanager.image.tag }}
          imagePullPolicy: {{ .Values.configmanager.image.pullPolicy }}
          ports:
            - containerPort: 9100
            - containerPort: 9101
          volumeMounts:
            - name: "prometheus-config"
              mountPath: /etc/configs
          env:
            - name: PROM_ALERTCONFIG_PORT
              value: {{ .Values.configmanager.environment.promAlertconfigPort | quote }}
            - name: RULES_DIR
              value: {{ .Values.configmanager.environment.rulesDir | quote }}
            - name: PROMETHEUS_URL
              value: {{ .Values.configmanager.environment.prometheusURL | quote }}
            - name: ALERTMANAGER_CONFIG_PORT
              value: {{ .Values.configmanager.environment.alertmanagerConfigPort | quote }}
            - name: ALERTMANAGER_CONF_PATH
              value: {{ .Values.configmanager.environment.alertmanagerConfPath | quote }}
            - name: ALERTMANAGER_URL
              value: {{ .Values.configmanager.environment.alertmanagerURL | quote }}
          resources:
{{ toYaml .Values.configmanager.resources | indent 12 }}
{{- end }}
