{{/*
Copyright (c) 2018-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.
*/}}
{{- if .Values.prometheus.create }}
{{- $serviceName := print .Release.Name "-prometheus" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $serviceName }}
  labels:
    app.kubernetes.io/component: prometheus
{{ include "metrics.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: prometheus
{{ include "selector-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: prometheus
{{ include "selector-labels" . | indent 8 }}
    spec:
      {{- with .Values.prometheus.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheus.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.prometheus.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | trimSuffix "\n" | indent 8 }}
      {{- end }}

      volumes:
        - name: "prometheus-config"
{{ toYaml .Values.metrics.volumes.prometheusConfig.volumeSpec | indent 10 }}
        - name: "prometheus-data"
{{ toYaml .Values.metrics.volumes.prometheusData.volumeSpec | indent 10 }}

  {{ if .Values.prometheus.useMinikube }}
      initContainers:
        - name: volume-mount
          image: busybox
          command: ["sh", "-c", "chmod -R 777 /prometheusData /etc/configs"]
          volumeMounts:
          - name: prometheus-data
            mountPath: /prometheusData
          - name: prometheus-config
            mountPath: /etc/configs
  {{ end }}

      containers:
        - name: "prometheus"
          image: {{ required "prometheus.image.repository must be provided" .Values.prometheus.image.repository }}:{{ .Values.prometheus.image.tag }}
          imagePullPolicy: {{ .Values.prometheus.image.pullPolicy }}
          volumeMounts:
            - name: "prometheus-config"
              mountPath: /etc/prometheus
              readOnly: true
            - name: "prometheus-data"
              mountPath: /data
          ports:
            - containerPort: 9090
          args: ['--config.file=/etc/prometheus/prometheus.yml',
                 '--storage.tsdb.retention.time={{ .Values.prometheus.retention.time }}',
                 '--storage.tsdb.path=/data',
                 '--web.enable-lifecycle']
          livenessProbe:
            httpGet:
              path: /graph
              port: 9090
            initialDelaySeconds: 10
            periodSeconds: 30
          resources:
{{ toYaml .Values.prometheus.resources | indent 12 }}
{{- end}}
