---
swagger: '2.0'

magma-gen-meta:
  go-package: magma/lte/cloud/go/services/subscriberdb/obsidian/models
  dependencies:
    - 'orc8r/cloud/go/models/swagger-common.yml'
    - 'orc8r/cloud/go/services/orchestrator/obsidian/models/swagger.v1.yml'
    - 'lte/cloud/go/services/policydb/obsidian/models/swagger.v1.yml'
  temp-gen-filename: lte-subscriberdb-swagger.yml
  output-dir: lte/cloud/go/services/subscriberdb/obsidian
  types:
    - go-struct-name: Subscriber
      filename: subscriber_swaggergen.go
    - go-struct-name: LteSubscription
      filename: lte_subscription_swaggergen.go
    - go-struct-name: SubscriberStatus
      filename: subscriber_status_swaggergen.go
    - go-struct-name: SubProfile
      filename: sub_profile_swaggergen.go
    - go-struct-name: IcmpStatus
      filename: icmp_status_swaggergen.go
    - go-struct-name: MutableSubscriber
      filename: mutable_subscriber_swaggergen.go

info:
  title: LTE Subscriber Management
  description: LTE REST APIs
  version: 1.0.0

basePath: /magma/v1

paths:
  /lte/{network_id}/subscribers:
    get:
      summary: List subscribers in the network
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
      responses:
        '200':
          description: List of all the subscribers in the network
          schema:
            type: object
            additionalProperties:
              $ref: '#/definitions/subscriber'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
    post:
      summary: Add a new subscriber to the network
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - in: body
          name: subscriber
          description: Subscriber that needs to be added
          required: true
          schema:
            $ref: '#/definitions/mutable_subscriber'
      responses:
        '201':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /lte/{network_id}/subscribers/{subscriber_id}:
    get:
      summary: Retrieve the subscriber info
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Subscriber Info
          schema:
            $ref: '#/definitions/subscriber'
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
    put:
      summary: Modify subscriber info
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
        - in: body
          name: subscriber
          description: Subscriber Info
          required: true
          schema:
            $ref: '#/definitions/mutable_subscriber'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'
    delete:
      summary: Remove a subscriber from the network
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /lte/{network_id}/subscribers/{subscriber_id}/lte/sub_profile:
    put:
      summary: Change a subscriber's data profile
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
        - in: body
          name: profile_name
          description: New profile name
          required: true
          schema:
            $ref: '#/definitions/sub_profile'
      responses:
        '204':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /lte/{network_id}/subscribers/{subscriber_id}/activate:
    post:
      summary: Activate a subscriber
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

  /lte/{network_id}/subscribers/{subscriber_id}/deactivate:
    post:
      summary: Deactivate a subscriber
      tags:
        - Subscribers
      parameters:
        - $ref: './orc8r-swagger-common.yml#/parameters/network_id'
        - $ref: './lte-policydb-swagger.yml#/parameters/subscriber_id'
      responses:
        '200':
          description: Success
        default:
          $ref: './orc8r-swagger-common.yml#/responses/UnexpectedError'

definitions:
  subscriber:
    type: object
    required:
      - id
      - lte
    properties:
      id:
        $ref: './lte-policydb-swagger.yml#/definitions/subscriber_id'
      name:
        type: string
        description: 'Optional name associated with the subscriber'
        example: 'Jane Doe'
      lte:
        $ref: '#/definitions/lte_subscription'
      active_base_names:
        type: array
        items:
          $ref: './lte-policydb-swagger.yml#/definitions/base_name'
        x-omitempty: true
        description: 'Base names which are active for this subscriber'
        example:
          - 'base_name_1'
          - 'base_name_2'
      active_policies:
        type: array
        items:
          $ref: './lte-policydb-swagger.yml#/definitions/policy_id'
        x-omitempty: true
        description: 'Policies which are active for this subscriber'
        example:
          - 'rule1'
          - 'rule2'
      active_apns:
        $ref: '#/definitions/apn_list'
      monitoring:
        $ref: '#/definitions/subscriber_status'
      state:
        $ref: '#/definitions/subscriber_state'

  mutable_subscriber:
    description: Subset of subscriber field which are mutable
    type: object
    required:
      - id
      - lte
    properties:
      id:
        $ref: './lte-policydb-swagger.yml#/definitions/subscriber_id'
      name:
        type: string
        description: 'Name for the subscriber'
        example: 'Jane Doe'
      lte:
        $ref: '#/definitions/lte_subscription'
      active_base_names:
        type: array
        items:
          $ref: './lte-policydb-swagger.yml#/definitions/base_name'
        x-omitempty: true
        description: 'Base names which are active for this subscriber'
        example:
          - 'base_name_1'
          - 'base_name_2'
      active_policies:
        type: array
        items:
          $ref: './lte-policydb-swagger.yml#/definitions/policy_id'
        x-omitempty: true
        description: 'Policies which are active for this subscriber'
        example:
          - 'rule1'
          - 'rule2'
      active_apns:
        $ref: '#/definitions/apn_list'

  lte_subscription:
    type: object
    required:
      - state
      - auth_algo
      - auth_key
      - sub_profile
    properties:
      state:
        type: string
        enum:
          - INACTIVE
          - ACTIVE
        x-nullable: false
      auth_algo:
        type: string
        enum:
          - MILENAGE
        x-nullable: false
      auth_key:
        type: string
        format: byte
        example: "AAAAAAAAAAAAAAAAAAAAAA=="
        x-nullable: false
      auth_opc:
        type: string
        format: byte
        example: 'AAECAwQFBgcICQoLDA0ODw=='
      sub_profile:
        $ref: '#/definitions/sub_profile'

  sub_profile:
    type: string
    minLength: 1
    example: 'default'

  subscriber_state:
    type: object
    description: EPC state for a subscriber
    properties:
      s1ap:
        $ref: '#/definitions/untyped_mme_state'
      mme:
        $ref: '#/definitions/untyped_mme_state'
      spgw:
        $ref: '#/definitions/untyped_mme_state'
      mobility:
        description: 'IP addresses which have been allocated for this subscriber'
        type: array
        items:
          $ref: '#/definitions/subscriber_ip_allocation'
        x-omitempty: true

  untyped_mme_state:
    type: object
    description: Arbitrary untyped JSON object that represents replicated MME state

  subscriber_ip_allocation:
    type: object
    description: An IP address which has been allocated for a subscriber for a specific APN
    required:
      - apn
      - ip
    properties:
      apn:
        type: string
        minLength: 1
        x-nullable: false
        example: 'oai.ipv4'
      ip:
        type: string
        format: ipv4
        example: '192.168.100.2'
        minLength: 1
        x-nullable: false


  subscriber_status:
    type: object
    description: Status of a subscriber device
    properties:
      icmp:
        $ref: '#/definitions/icmp_status'

  icmp_status:
    type: object
    description: ICMP status of a subscriber device
    required:
      - latency_ms
    properties:
      latency_ms:
        type: number
        format: float
        example: 12.34
      last_reported_time:
        type: integer
        format: int64

  apn_list:
    type: array
    description: 'APNs that are allowed for this subscriber'
    items:
      type: string
      x-nullable: false
      example: 'internet'
    x-omitempty: true
    example:
      - 'internet'
      - 'ims'
