- name: Elasticsearch | Ensure stable helm repo
  command: helm repo add stable https://charts.helm.sh/stable/

- name: Elasticsearch | Ensure namespace
  command: kubectl create ns {{ magma_namespace }}
  failed_when: false

- name: Elasticsearch | Update repo metadata
  command: helm repo update

- name: Elasticsearch | Ensure charts dir
  file:
    path: "{{ charts_dir }}"
    state: directory
    recurse: yes

- name: Elasticsearch | Template out helm chart values
  template:
    src: elasticsearch-values.yaml.j2
    dest: "{{ charts_dir }}/{{ item }}-values.yaml"
  with_items:
    - elasticsearch
    - elasticsearch-curator

- name: Elasticsearch | Install/upgrade helm charts
  command: helm upgrade --install -n {{ magma_namespace }} {{ item }} stable/{{ item }} -f {{ charts_dir }}/{{ item }}-values.yaml
  with_items:
    - elasticsearch
    - elasticsearch-curator
